

name: action-cat
description: This action will print the contents of a file to the console

runs:
  using: composite
  steps:
    - name: cat-file
      shell: bash
      run: |
        cat notes.txt