name: My-Workflow

on: 
    push:
        branches:
            - main

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step-1
              id: step-1
              run: |
                bike="vigory300"
                echo "my-bike=$bike" >> $GITHUB_OUTPUT
              
            - name: step-2
              id: step-2
              run: |
                echo "my-bike from step-1: ${{ steps.step-1.outputs.my-bike }}"
           
            - name: step-3
              run: |
                model="2023"
                echo "bike-model=$model" >> $GITHUB_ENV
                echo "the model is ${{ env.bike-model }}"
                