name: My-Workflow

on: 
    push:
        branches:
            - main

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: name-of-author
              run: echo "Author: ${{ github.actor }}"
