   
name: workflow-1

on:
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: step-1
        uses: ./actions/cat
        with:
          username: "Eyad Rezk"
          age: "23"
          area: "Fustat"